### ISSUE TITLE
HMA should support schemas with multiple foreign keys to the same parent

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/SDV#1508]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.2.1
* Python version: Any
* Operating System: Any

### Error Description

It seems like the `HMASynthesizer` fails during sampling on some datasets that have multiple foreign keys pointing to the same parent key.

### Steps to reproduce

```python
from sdv.multi_table import HMASynthesizer
from sdv.datasets.demo import get_available_demos, download_demo

data, metadata = download_demo('multi_table', 'mutagenesis_v1')

synthesizer = HMASynthesizer(metadata)
synthesizer.fit(data)
sampled = synthesizer.sample()
```

```
Traceback (most recent call last):  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/sdv/data_processing/data_processor.py", line 756, in reverse_transform    reversed_data[column_name] = reversed_data[column_name].astype(dtype)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/pandas/core/generic.py", line 6324, in astype    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 451, in astype    return self.apply(  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 352, in apply    applied = getattr(b, f)(**kwargs)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 511, in astype    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe    new_values = astype_array(values, dtype, copy=copy)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array    values = _astype_nansafe(values, dtype, copy=copy)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 105, in _astype_nansafe    return _astype_float_to_int_nansafe(arr, dtype, copy)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 150, in _astype_float_to_int_nansafe    raise IntCastingNaNError(pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):  File "/Users/frances/Documents/enterprise/notebooks/hma_test.py", line 28, in <module>    synth.sample()  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/sdv/multi_table/base.py", line 399, in sample    sampled_data = self._sample(scale=scale)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/sdv/sampling/hierarchical_sampler.py", line 193, in _sample    self._sample_table(  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/sdv/sampling/hierarchical_sampler.py", line 136, in _sample_table    self._add_child_rows(  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/sdv/sampling/hierarchical_sampler.py", line 103, in _add_child_rows    sampled_rows = self._sample_rows(child_synthesizer, num_rows)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/sdv/sampling/hierarchical_sampler.py", line 71, in _sample_rows    return synthesizer._sample_batch(int(num_rows), keep_extra_columns=True)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/sdv/single_table/base.py", line 704, in _sample_batch    sampled, num_valid = self._sample_rows(  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/sdv/single_table/base.py", line 621, in _sample_rows    sampled = self._data_processor.reverse_transform(raw_sampled)  File "/Users/frances/.pyenv/versions/sdv-enterprise/lib/python3.10/site-packages/sdv/data_processing/data_processor.py", line 770, in reverse_transform    raise ValueError(e)ValueError: Cannot convert non-finite values (NA or inf) to integer
```

**Comment by npatki** [comment]
Turning this into a feature request, as HMA was not explicitly tested for this case.

**Comment by npatki** [comment]
This has since been fixed. Verified on SDV 1.12.0
