### ISSUE TITLE
RuntimeError: Expected p_in >= 0 && p_in <= 1 to be true, but got false

### ISSUE THREAD

**Issue by elenagenf** [sdv-dev/SDV#300]
### Environment Details

* SDV version: 0.5.0
* Python version: 3.7.9
* Operating System: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-122-generic ppc64le)

### Error Description

I train a PAR model to generate heart rate timeseries. When I try to sample from the data, I receive the a runtime error. Would you suggest to downgrade or upgrade pytorch or is this error attributed to something else?

### Steps to reproduce

This is a screenshot of the first data points, where letters are ids:
![Screenshot 2021-01-22 at 16 49 30](https://user-images.githubusercontent.com/73545219/105514831-4081c280-5cd4-11eb-9d10-f0b8b679fce8.png)

```
from sdv.timeseries import PAR

data = pd.read_csv('heart_rate.csv')

entity_columns = ['id']
sequence_index = 'charttime'

model = PAR(
    entity_columns=entity_columns,
    sequence_index=sequence_index)

model.fit(data)
samples = model.sample(1)


Traceback (most recent call last):
  File "train_ts.py", line 27, in <module>
    samples = model.sample(1)
  File "/home/elena/.local/lib/python3.7/site-packages/sdv/timeseries/base.py", line 262, in sample
    sampled = self._sample(context, sequence_length)
  File "/home/elena/.local/lib/python3.7/site-packages/sdv/timeseries/deepecho.py", line 114, in _sample
    sequence = self._model.sample_sequence(context_values, sequence_length)
  File "/home/elena/.local/lib/python3.7/site-packages/deepecho/models/par.py", line 554, in sample_sequence
    x, log_likelihood = self._sample_sequence(context, min_length, max_length)
  File "/home/elena/.local/lib/python3.7/site-packages/deepecho/models/par.py", line 511, in _sample_sequence
    next_x, ll = self._sample_state(self._model(x, context)[-1:, :, :])
  File "/home/elena/.local/lib/python3.7/site-packages/deepecho/models/par.py", line 471, in _sample_state
    x[0, 0, missing_idx] = dist.sample()
  File "/opt/anaconda3/envs/powerai/lib/python3.7/site-packages/torch/distributions/bernoulli.py", line 89, in sample
    return torch.bernoulli(self.probs.expand(shape))
RuntimeError: Expected p_in >= 0 && p_in <= 1 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

**Comment by csala** [comment]
Hi @elenagenf 

I think that the problem may be that you are not passing the `charttime` column as a datetime but rather as a string.

Can you try parsing it `data = pd.to_datetime(data['charttime'])` before calling `fit`?

**Comment by csala** [comment]
Closing this as a stalled conversation. Please feel free to reopen if there is more input on the topic.
