### ISSUE TITLE
ValueError: numpy.ndarray size changed,

### ISSUE THREAD

**Issue by VladPerervenko** [sdv-dev/SDV#406]
### Environment Details
Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.9.0
* Python version: 3.8.5
* Operating System: Win10 20H2 (19042.928)

### Error Description
`Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sdv.demo import load_timeseries_demo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdv\**init**.py", line 11, in <module>
    from sdv import constraints, evaluation, metadata, relational, tabular
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdv\evaluation.py", line 4, in <module>
    import sdmetrics
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdmetrics\**init**.py", line 11, in <module>
    from sdmetrics import (
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdmetrics\multi_table\**init**.py", line 3, in <module>
    from sdmetrics.multi_table import detection, multi_single_table
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdmetrics\multi_table\multi_single_table.py", line 7, in <module>
    from sdmetrics import single_table
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdmetrics\single_table\**init**.py", line 3, in <module>
    from sdmetrics.single_table import (
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdmetrics\single_table\bayesian_network.py", line 7, in <module>
    from pomegranate import BayesianNetwork
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\pomegranate\**init**.py", line 11, in <module>
    from .base import *
  File "pomegranate\base.pyx", line 1, in init pomegranate.base
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

>>> from sdv import load_demo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdv\**init**.py", line 11, in <module>
    from sdv import constraints, evaluation, metadata, relational, tabular
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdv\evaluation.py", line 4, in <module>
    import sdmetrics
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdmetrics\**init**.py", line 11, in <module>
    from sdmetrics import (
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdmetrics\multi_table\**init**.py", line 3, in <module>
    from sdmetrics.multi_table import detection, multi_single_table
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdmetrics\multi_table\multi_single_table.py", line 7, in <module>
    from sdmetrics import single_table
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdmetrics\single_table\**init**.py", line 3, in <module>
    from sdmetrics.single_table import (
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\sdmetrics\single_table\bayesian_network.py", line 7, in <module>
    from pomegranate import BayesianNetwork
  File "C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\pomegranate\**init**.py", line 11, in <module>
    from .base import *
  File "pomegranate\base.pyx", line 1, in init pomegranate.base
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

**Comment by FlorianRempel** [comment]
I also encountered this problem before. The most commonly found solution (that also worked for me) is to up- or downgrade your numpy version.

**Comment by VladPerervenko** [comment]
When installing pandas == 1.1
`(fastai) C:\Users\User>python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sdv import load_demo
>>> metadata, tables = load_demo(metadata=True)
>>> from sdv import SDV
>>> sdv = SDV()
>>> sdv.fit(metadata, tables)
C:\Users\User\AppData\Local\R-MINI~1\envs\fastai\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)`
Issues a warning, but works.
