### ISSUE TITLE
Optimization converged to parameters that are outside the range allowed by the distribution

### ISSUE THREAD

**Issue by skumarlabs** [sdv-dev/SDV#490]
### Environment Details

* SDV version: 0.10.1
* Python version: 3.8
* Operating System: Ubuntu 20.04 and MacOs Big Sur 11.4

### Error Description

While training any Copula based model i.e. GaussianCopula or CopulaGAN, the training is failing with following stacktrace. I am including logs as well in case any useful information is present there. Not able to share dataset as it is production data but it contains 24 categorical columns, 40 numerical columns with possible null values in both.
**It's worth noting that this is not happening in SDV 0.9.**

### Steps to reproduce

```
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py:5320: RuntimeWarning: divide by zero encountered in true_divide
  return c**2 / (c**2 - n**2)
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py:2606: RuntimeWarning: invalid value encountered in double_scalars
  Lhat = muhat - Shat*mu
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py:5311: RuntimeWarning: divide by zero encountered in power
  return cd2*x**(c-1)
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/copulas/univariate/truncated_gaussian.py:43: RuntimeWarning: invalid value encountered in double_scalars
  a = (self.min - loc) / scale
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/copulas/univariate/truncated_gaussian.py:44: RuntimeWarning: divide by zero encountered in double_scalars
  b = (self.max - loc) / scale
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py:639: RuntimeWarning: invalid value encountered in sqrt
  sk = 2*(b-a)*np.sqrt(a + b + 1) / (a + b + 2) / np.sqrt(a*b)
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/optimize/minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/optimize/minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last five Jacobian evaluations.
  warnings.warn(msg, RuntimeWarning)
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/optimize/minpack.py:175: RuntimeWarning: The number of calls to function has reached maxfev = 600.
  warnings.warn(msg, RuntimeWarning)
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py:615: RuntimeWarning: divide by zero encountered in _beta_cdf
  return _boost._beta_cdf(x, a, b)
/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/optimize/optimize.py:761: RuntimeWarning: invalid value encountered in subtract
  np.max(np.abs(fsim[0] - fsim[1:])) <= fatol):
Traceback (most recent call last):
  File "mem_test2.py", line 127, in <module>
    train()
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/memory_profiler.py", line 1142, in wrapper
    val = prof(func)(*args, **kwargs)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/memory_profiler.py", line 717, in f
    return func(*args, **kwds)
  File "mem_test2.py", line 105, in train
    model.fit(temp)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/sdv/tabular/base.py", line 123, in fit
    self._fit(transformed)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/sdv/tabular/copulas.py", line 282, in _fit
    self._model.fit(table_data)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/copulas/__init__.py", line 216, in decorated
    return function(self, X, *args, **kwargs)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/copulas/multivariate/gaussian.py", line 108, in fit
    univariate.fit(column)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/copulas/univariate/base.py", line 225, in fit
    self._instance = select_univariate(selection_sample, self.candidates)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/copulas/univariate/selection.py", line 25, in select_univariate
    instance.fit(X)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/copulas/univariate/base.py", line 599, in fit
    self._fit(X)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/copulas/univariate/beta.py", line 28, in _fit
    a, b = beta.fit(X, loc=loc, scale=scale)[0:2]
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 62, in wrapper
    return fun(self, *args, **kwds)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 662, in fit
    return super().fit(data, *args, **kwds)
  File "/Users/user/envs/sdv10-1/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py", line 2505, in fit
    raise Exception("Optimization converged to parameters that are "
Exception: Optimization converged to parameters that are outside the range allowed by the distribution.
```

### Ability to contribute
Yes, not much though in terms of advance statistics.

**Comment by csala** [comment]
Interesting. Thanks for reporting this @skumarlabs! We'll dig into it and see if we manage to reproduce it and figure out where it comes from.

**Comment by onacrame** [comment]
I also get this error when selecting "bounded" distributions by default if I have a uniquecombinations constraint

**Comment by fealho** [comment]
Hi @skumarlabs @onacrame I was unable to reproduce this error. Could either of you share the relevant snippet of code? Also, if you could provide some summary statistics of the dataset you used, that could be very helpful.

**Comment by onacrame** [comment]
I've also recently had this issue on this 15,000 row data set and the corresponding null count.  I'm not sure it's any on particular field creating the error.  But ultimately it's a failed convergence issue.  And in this cause I don't impose a specific distribution in the CopulaGan fit function.  Note, that I had previously been able to synthesise samples off another version of this data set with fewer nulls in some fields however, the nulls are there by design and filling them with a value is not an option.  When I fill all nulls with 0 the model fits just fine.

![image](https://user-images.githubusercontent.com/11838381/126619499-448ae1a7-f591-40c1-ad58-d456e7f63d21.png)

**Comment by onacrame** [comment]
actually it was a single column causing the issue (A37 I believe in this anonymised version I pasted), generating the failed optimization error message (and not even the columns with the highest null count.  I filled nulls in that columns with zero and the model proceeds to fit as expected.

**Comment by csala** [comment]
> changing the scipy version doesn't seem to work.

@onacrame could you clarify what you tried?

When investigating this it seemed like the problem comes from the latest Scipy version, 1.7.0, which now validates the learned parameters where before it would just take whatever it had learned even if they were invalid (and therefore generated wrong values)

So it would seem that restricting the `scipy` version to `<1.7` would fix the problem, at least until we find another way to work around this.

**Comment by weirdfishs** [comment]
Was there any solution or workaround found for this issue? I am unable to intall a version less than 1.7 of scipy on the system that I have access to for testing, but I would like to try and understand what is causing this issue.

I am currently running SDV version 1.18.0 and in a virtual python environment version 3.10.12. I am using the KDD CUP 1999 network intrusion dataset, specifically the 10 percent set. For whatever reason, I am able to fit perfectly fine when using a further 1% of this set. I am currently unsure of how to fix this, as I cannot find many results for this issue.

**Comment by npatki** [comment]
Hi @weirdfishs, as this current issue is ~4 years old, I have created a separate issue at #2390 to discuss your problem.
