### ISSUE TITLE
Error while attempting HMA1.sample

### ISSUE THREAD

**Issue by matteckman** [sdv-dev/SDV#591]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 0.12
* Python version: 3.8
* Operating System: Mac OS 

### Error Description

I was trying to generate data from an HMA1 model that I generated off of 5 tables in a Postgresql databse, and I keep getting this error message:

`AttributeError: 'NoneType' object has no attribute 'ppf'`

I tried using just one table in `.sample()` but that gave me the same error message.

### Steps to reproduce

I can't post all the code I used to fit the HMA1 model as it's confidential, but the basic steps are below. These first steps ran without any errors:
* Connect to Postgresql database using pyodbc
* Do a SELECT from different tables using pandas.read_sql_query()
* Set up the metadata as described in the documentation via `model.add_table()`
* Set up metadata with command `model = HMA1(metadata)`
* Combine the different data frames I loaded from the database into a dictionary `tables = { 'tableName': tableDF }`
* Ran `model.fit(tables)`
* Ran `model.save('....pkl')`

Then I downloaded the pkl file to my local machine and ran this, which generates the error:
* `from sdv.relational import HMA1`
* `model = HMA1.load('....pkl')`
* `new_data = model.sample(num_rows=5)`
* then I get the error I pasted above, and here's the full trace (This trace is not from my attempt to sample from all tables, it's from my folllowing attempt to sample from 1 table to see if that changed anything, but it didn't. The trace was the same for both scenarios.) 

```Traceback (most recent call last):
  File "write_sql_server_db.py", line 10, in <module>
    new_data = model.sample('test', num_rows=5, sample_children=False)
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/sdv/relational/base.py", line 184, in sample
    return self._sample(table_name, num_rows, sample_children)
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/sdv/relational/hma.py", line 461, in _sample
    sampled_data = self._sample_table(table_name, num_rows, sample_children)
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/sdv/relational/hma.py", line 426, in _sample_table
    table_rows = self._sample_rows(model, table_name, num_rows)
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/sdv/relational/hma.py", line 318, in _sample_rows
    sampled = model.sample(num_rows)
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/sdv/tabular/base.py", line 432, in sample
    return self._sample_batch(num_rows, max_retries, max_rows_multiplier)
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/sdv/tabular/base.py", line 298, in _sample_batch
    sampled, num_valid = self._sample_rows(
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/sdv/tabular/base.py", line 227, in _sample_rows
    sampled = self._sample(num_rows)
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/sdv/tabular/copulas.py", line 319, in _sample
    return self._model.sample(num_rows, conditions=conditions)
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/copulas/__init__.py", line 36, in wrapper
    return function(self, *args, **kwargs)
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/copulas/multivariate/gaussian.py", line 254, in sample
    output[column_name] = univariate.percent_point(cdf)
  File "/Users/matteckman/opt/anaconda3/lib/python3.8/site-packages/copulas/univariate/base.py", line 554, in percent_point
    return self._model.ppf(U)```

**Comment by matteckman** [comment]
So I found a solution. I was running the `model.fit()` stage in a Python 3.6 container, and the `model.sample()` stage in 3.9.7. I ran `model.sample()` in the same container and it worked.

**Comment by katxiao** [comment]
Hi @matteckman, thanks for following up with your resolution! 

I'm going to close this issue, but if you want to discuss your use case further, feel free to open another issue or join our [slack workspace](https://sdv.dev/SDV/#join-our-slack-workspace).
