### ISSUE TITLE
Not possible with Unique constraint containing foreign key?

### ISSUE THREAD

**Issue by halvorot** [sdv-dev/SDV#813]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.14.1
* Python version: 3.9
* Operating System: Windows

### Problem description
I am having trouble with adding a Unique constraint to two fields in my database (https://dev.mysql.com/doc/employee/en/).
I get a KeyError on 'emp_no' in the pandas groupby function loacted in the is_valid function of the Unique constraint. I am wondering if this is because 'emp_no' is a foreign key to another table? Or could there be another reason/bug?

This is the traceback:
`Traceback (most recent call last):
  File "C:\Users\hteigen\Documents\GIT\sdv-app\sdv-app-backend\.\main.py", line 61, in load_train
    model.train_model()
  File "C:\Users\hteigen\Documents\GIT\sdv-app\sdv-app-backend\.\src\Model.py", line 19, in train_model
    self.model.fit(tables=self.raw_data_dict)
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\sdv\relational\base.py", line 63, in fit
    self._fit(tables)
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\sdv\relational\hma.py", line 281, in _fit
    self._model_table(table_name, tables)
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\sdv\relational\hma.py", line 244, in _model_table
    table = self._extend_table(table, tables, table_name)
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\sdv\relational\hma.py", line 155, in _extend_table
    child_table = self._model_table(child_name, tables)
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\sdv\relational\hma.py", line 251, in _model_table
    model.fit(table)
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\sdv\tabular\base.py", line 152, in fit
    transformed = self._metadata.transform(data)
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\sdv\metadata\table.py", line 658, in transform
    self._validate_data_on_constraints(data)
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\sdv\metadata\table.py", line 629, in _validate_data_on_constraints
    if not constraint.is_valid(data).all():
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\sdv\constraints\tabular.py", line 1153, in is_valid
    return table_data.groupby(self.columns).cumcount() == 0
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\pandas\core\frame.py", line 7712, in groupby
    return DataFrameGroupBy(
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\pandas\core\groupby\groupby.py", line 882, in __init__
    grouper, exclusions, obj = get_grouper(
  File "C:\Users\hteigen\Anaconda3\envs\sdvappenv\lib\site-packages\pandas\core\groupby\grouper.py", line 882, in get_grouper
    raise KeyError(gpr)
KeyError: 'emp_no'`

The following metadata exists for the table "dept_emp" connecting the departments and employees tables.
```json
"dept_emp": {
            "fields": {
                "emp_no": {
                    "type": "id",
                    "subtype": "integer",
                    "ref": {
                        "table": "employees",
                        "field": "emp_no"
                    }
                },
                "dept_no": {
                    "type": "id",
                    "subtype": "string"
                },
                "from_date": {
                    "type": "datetime"
                },
                "to_date": {
                    "type": "datetime"
                }
            },
            "constraints": [
                {
                    "constraint": "sdv.constraints.tabular.Unique",
                    "columns": [
                        "emp_no",
                        "dept_no"
                    ]
                }
            ],
            "primary_key": "dept_no"
        },
```
Here is the total visualization of the metadata:
![image](https://user-images.githubusercontent.com/36247551/169769339-eba147f5-aee5-41ba-936e-5f144d264605.png)

**Comment by npatki** [comment]
Hi @halvorot, what logic are using the `Unique` constraint to capture?

The SDV already guarantees that every primary key is unique in the table. Since `dept_no` is a primary key, it will be unique. Therefore, the combination of `dept_no, emp_no` is also unique -- no constraint is needed.

**Comment by halvorot** [comment]
Sorry, that was not the best example. It is really supposed to be a composite primary key (emp_no, dept_no) but I know that is not supported yet.  I will try to find another example when i encounter one and rather start a new issue.
